package com.java.project;

/**
 * This class is been called when user clicks on Query button.
 * It asks user to enter the country name and code and full name of the country will be displayed 
 * automatically once user type 3 letters of the country.
 * once the country name and country code are generated,the text fields are seteditable to false.
 * On clicking enter button the airports and runways at each airport.
 * 
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * 
 * @author Shanta Hosmani
 *
 */
public class QuerryFun implements ActionListener {
	public void actionPerformed(ActionEvent ae) {
		/**
		 * JFrame,JPanel,JLabel,JTextField,JButtons are created and initialized.
		 */
		JFrame frame2 = new JFrame("Airport demo project at Lunatech");
		frame2.setVisible(true);
		frame2.setSize(500, 500);
		JLabel label = new JLabel(" Please enter country name ");

		JComboBox name_box = new JComboBox();

		label.setFont(new Font("Serif", Font.BOLD, 20));
		JLabel name = new JLabel("country name");
		JLabel code = new JLabel("country code");

		JPanel panel = new JPanel(new GridBagLayout());
		panel.setBackground(Color.GRAY);

		JTextField country_name = new JTextField(10);
		JTextField country_code = new JTextField(10);
		country_code.setEditable(false);

		JButton enter = new JButton("Enter");
		enter.setBackground(Color.WHITE);

		GridBagConstraints c = new GridBagConstraints();
		c.insets = new Insets(10, 10, 10, 10);

		ArrayList<String> items = new ArrayList<>();

		/**
		 * DocumentListener is added to the textfield of country name so that
		 * the user entered text can be read.
		 * 
		 */

		country_name.getDocument().addDocumentListener(new DocumentListener() {

			public void changedUpdate(DocumentEvent e) {

			}

			public void insertUpdate(DocumentEvent e) {

				if ((country_name.getText().length()) == 3) {
					autoGeneratedata();
					System.out.println("done:-)");
				}

			}

			public void removeUpdate(DocumentEvent e) {

			}

			/**
			 * This function is called when use types 3 letter for the country
			 * name textfield. It fetch the textfield and check in the database
			 * of counties for the proper match. It also set country full
			 * country name and country code of that country.
			 */
			public void autoGeneratedata() {

				// Database credentials
				final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
				final String DB_URL = "jdbc:mysql://localhost/airportdb?useSSL=false";
				final String USER = "root";
				final String PASS = "root";
				Connection conn = null;
				Statement stmt = null;
				String cname = null;
				String ccode = null;
				ResultSet rs = null;
				cname = country_name.getText();

				try {

					// Register JDBC driver
					Class.forName(JDBC_DRIVER);

					// Open a connection
					conn = DriverManager.getConnection(DB_URL, USER, PASS);

					// Execute a query
					stmt = conn.createStatement();
					// ResultSet rs,rs2;

					String sql;
					// This query fetch country name which starts with entered 3
					// letters by user.
					sql = "select name from countries where name LIKE'" + cname + "%' ; ";
					rs = stmt.executeQuery(sql);

					// Extract data from result set
					while (rs.next()) {

						items.add(rs.getString("name"));
					}

					SwingUtilities.invokeLater(new Runnable() {
						public void run() {
							country_name.setText(items.get(0));
							// country_name.setEditable(false);
							System.out.println("country name after 1 query in run" + items.get(0));
							System.out.println(country_name.getText());
						}

					});// end of SwingUtility
					System.out.println("country name after 1 query" + items.get(0));
					System.out.println(country_name.getText());

					// String c = country_name.getText();
					String c = items.get(0);

					ResultSet rs2;

					String sql2 = "select code from countries where countries.name = '" + c + " ' ;";
					rs2 = stmt.executeQuery(sql2);

					if (items.size() == 1) {
						while (rs2.next()) {
							ccode = rs2.getString("code");
						}
						System.out.println(ccode);
						country_code.setText(ccode);
						System.out.println("country code after 2 nd query" + country_code.getText());
						enter.addActionListener(new TableAirport(country_name.getText(), country_code.getText()));

					}

					else {

						for (int k = 0; k <= (items.size() - 1); k++) {
							name_box.addItem(items.get(k));
						}
						name_box.setVisible(true);
						name_box.setEditable(true);
                        country_name.setEditable(false);

						ActionListener actionListener = new ActionListener() {
							public void actionPerformed(ActionEvent actionEvent) {
								String name = (String) name_box.getSelectedItem();
								SwingUtilities.invokeLater(new Runnable() {
									public void run() {
										
										country_name.setText(name);
									}
								});
								System.out.println("Selected: " + name_box.getSelectedItem());

								enter.addActionListener(new TableAirport(name, country_code.getText()));

							}
						};
						name_box.addActionListener(actionListener);

					}

					System.out.println("at end");
					// Clean-up environment
					rs.close();
					stmt.close();
					conn.close();
				} catch (SQLException se) {
					// Handle errors for JDBC
					se.printStackTrace();
				} catch (Exception ee) {
					// Handle errors for Class.forName
					ee.printStackTrace();
				} finally {
					// finally block used to close resources
					try {
						if (stmt != null)
							stmt.close();
					} catch (SQLException se2) {
					} // nothing we can do
					try {
						if (conn != null)
							conn.close();
					} catch (SQLException se) {
						se.printStackTrace();
					} // end finally try

				} // end of main try

			}

		});

		System.out.println("Thank u");

		c.gridx = 0;
		c.gridy = 0;
		panel.add(label, c);

		c.gridx = 0;
		c.gridy = 1;
		panel.add(name, c);
		c.gridx = 1;
		c.gridy = 1;
		panel.add(country_name, c);
		c.gridx = 0;
		c.gridy = 3;
		panel.add(name_box, c);
		name_box.setVisible(false);

		c.gridx = 0;
		c.gridy = 4;
		panel.add(code, c);
		c.gridx = 1;
		c.gridy = 4;
		panel.add(country_code, c);

		c.gridx = 0;
		c.gridy = 6;
		panel.add(enter, c);

		frame2.add(panel);

	}
}
